name: GoBuild
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # image: golang:13-alpi
    steps:
      # - name: Set up Go 1.13
      #   uses: actions/setup-go@v1
      #   with:
      #     go-version: 1.13
      #   id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: |-
          mkdir build/

          CGO_ENABLED=0
          GOOS=linux
          GOARCH=amd64

          go build -ldflags="-w -s" -mod vendor -v -o build/envdir

      - name: Upload compiled binary
        uses: actions/upload-artifact@master
        with:
          name: envdir
          path: envdir
